In [140]:
import tensorflow as tf

In [141]:
sess = tf.InteractiveSession()

In [142]:
import numpy as np

In [370]:
a = np.arange(0, 6 * 8 * 10)
a = a.reshape(-1,8,10)
b = np.array([0,1,2,0,1,2])

In [401]:
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79]],

       [[ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159]],

       [[160, 161, 162, 163, 164, 16

In [411]:
k = np.random.randint(0,8)


In [412]:
np.roll(a=a, axis=1,shift= k)

array([[[ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69]],

       [[150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]],

       [[230, 231, 232, 233, 234, 23

In [372]:
def mapper(x,y):
    k = tf.random_uniform([], minval=0,maxval=7,dtype=tf.int32)
    x = tf.manip.roll(x,axis=1,shift=k)
    return x, y

In [388]:
dt = tf.data.Dataset.from_tensor_slices((a,b)).batch(1)
dt = dt.map(map_func=mapper, num_parallel_calls=2)

In [394]:
it = dt.make_one_shot_iterator()

for i in range(11):
    p, q = sess.run(it.get_next())
    print p

[[[60 61 62 63 64 65 66 67 68 69]
  [70 71 72 73 74 75 76 77 78 79]
  [ 0  1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18 19]
  [20 21 22 23 24 25 26 27 28 29]
  [30 31 32 33 34 35 36 37 38 39]
  [40 41 42 43 44 45 46 47 48 49]
  [50 51 52 53 54 55 56 57 58 59]]]
[[[100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]
  [150 151 152 153 154 155 156 157 158 159]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]]]
[[[220 221 222 223 224 225 226 227 228 229]
  [230 231 232 233 234 235 236 237 238 239]
  [160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]]]
[[[240 241 242 243

OutOfRangeError: End of sequence
	 [[Node: IteratorGetNext_338 = IteratorGetNext[output_shapes=[[?,8,10], [?]], output_types=[DT_INT64, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_148)]]

Caused by op u'IteratorGetNext_338', defined at:
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2714, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2818, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-394-ce8532e7612d>", line 4, in <module>
    p, q = sess.run(it.get_next())
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 370, in get_next
    name=name)), self._output_types,
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1466, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/minhb/venv/python2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): End of sequence
	 [[Node: IteratorGetNext_338 = IteratorGetNext[output_shapes=[[?,8,10], [?]], output_types=[DT_INT64, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_148)]]


In [396]:
p.shape

(1, 8, 10)

In [397]:
q.shape

(1,)

In [249]:
b.shape

(2,)

In [185]:
a

array([[[160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
        [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
        [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
        [190, 191, 192, 193, 194, 195, 196, 197, 198, 199],
        [200, 201, 202, 203, 204, 205, 206, 207, 208, 209],
        [210, 211, 212, 213, 214, 215, 216, 217, 218, 219],
        [220, 221, 222, 223, 224, 225, 226, 227, 228, 229],
        [230, 231, 232, 233, 234, 235, 236, 237, 238, 239]],

       [[240, 241, 242, 243, 244, 245, 246, 247, 248, 249],
        [250, 251, 252, 253, 254, 255, 256, 257, 258, 259],
        [260, 261, 262, 263, 264, 265, 266, 267, 268, 269],
        [270, 271, 272, 273, 274, 275, 276, 277, 278, 279],
        [280, 281, 282, 283, 284, 285, 286, 287, 288, 289],
        [290, 291, 292, 293, 294, 295, 296, 297, 298, 299],
        [300, 301, 302, 303, 304, 305, 306, 307, 308, 309],
        [310, 311, 312, 313, 314, 315, 316, 317, 318, 319]]])

In [114]:
np.roll(a=a,axis=1,shift=2)

array([[[-220, -221, -222, -223, -224, -225, -226, -227, -228, -229],
        [-230, -231, -232, -233, -234, -235, -236, -237, -238, -239],
        [-160, -161, -162, -163, -164, -165, -166, -167, -168, -169],
        [-170, -171, -172, -173, -174, -175, -176, -177, -178, -179],
        [-180, -181, -182, -183, -184, -185, -186, -187, -188, -189],
        [-190, -191, -192, -193, -194, -195, -196, -197, -198, -199],
        [-200, -201, -202, -203, -204, -205, -206, -207, -208, -209],
        [-210, -211, -212, -213, -214, -215, -216, -217, -218, -219]],

       [[-300, -301, -302, -303, -304, -305, -306, -307, -308, -309],
        [-310, -311, -312, -313, -314, -315, -316, -317, -318, -319],
        [-240, -241, -242, -243, -244, -245, -246, -247, -248, -249],
        [-250, -251, -252, -253, -254, -255, -256, -257, -258, -259],
        [-260, -261, -262, -263, -264, -265, -266, -267, -268, -269],
        [-270, -271, -272, -273, -274, -275, -276, -277, -278, -279],
        [-280, -28

In [173]:
k = tf.random_uniform([],
    minval=0,
    maxval=7,
    dtype=tf.int32,
    seed=None,
    name=None
)

In [174]:
sess.run(k)

1

In [233]:
x =tf.placeholder(shape=(None, 8,10),dtype=tf.int32)
v = tf.manip.roll(x,axis=1,shift=1)

In [234]:
sess.run(v, feed_dict={x:a})

array([[[470, 471, 472, 473, 474, 475, 476, 477, 478, 479],
        [400, 401, 402, 403, 404, 405, 406, 407, 408, 409],
        [410, 411, 412, 413, 414, 415, 416, 417, 418, 419],
        [420, 421, 422, 423, 424, 425, 426, 427, 428, 429],
        [430, 431, 432, 433, 434, 435, 436, 437, 438, 439],
        [440, 441, 442, 443, 444, 445, 446, 447, 448, 449],
        [450, 451, 452, 453, 454, 455, 456, 457, 458, 459],
        [460, 461, 462, 463, 464, 465, 466, 467, 468, 469]],

       [[390, 391, 392, 393, 394, 395, 396, 397, 398, 399],
        [320, 321, 322, 323, 324, 325, 326, 327, 328, 329],
        [330, 331, 332, 333, 334, 335, 336, 337, 338, 339],
        [340, 341, 342, 343, 344, 345, 346, 347, 348, 349],
        [350, 351, 352, 353, 354, 355, 356, 357, 358, 359],
        [360, 361, 362, 363, 364, 365, 366, 367, 368, 369],
        [370, 371, 372, 373, 374, 375, 376, 377, 378, 379],
        [380, 381, 382, 383, 384, 385, 386, 387, 388, 389]]], dtype=int32)

In [ ]:

k = np.